<?php

/**
 * Baseimage_keyword_map
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $image_id
 * @property integer $keyword_id
 * 
 * @method integer           getImageId()    Returns the current record's "image_id" value
 * @method integer           getKeywordId()  Returns the current record's "keyword_id" value
 * @method image_keyword_map setImageId()    Sets the current record's "image_id" value
 * @method image_keyword_map setKeywordId()  Sets the current record's "keyword_id" value
 * 
 * @package    Mosaic
 * @subpackage model
 * @author     Philipp Steinmann
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseimage_keyword_map extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image_keyword_map');
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('keyword_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}