<?php

/**
 * Baseimages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $color
 * 
 * @method string getUrl()   Returns the current record's "url" value
 * @method string getColor() Returns the current record's "color" value
 * @method images setUrl()   Sets the current record's "url" value
 * @method images setColor() Sets the current record's "color" value
 * 
 * @package    Mosaic
 * @subpackage model
 * @author     Philipp Steinmann
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseimages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('images');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('color', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}