<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/09/05 15:07:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mosaic',
  'username' => 'root',
  'password' => 'p',
  'name' => 'doctrine',
)),);
