<?php

/**
 * images
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Mosaic
 * @subpackage model
 * @author     Philipp Steinmann
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class images extends Baseimages
{
}
