<?php

/**
 * image_keyword_mapTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class image_keyword_mapTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object image_keyword_mapTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('image_keyword_map');
    }
}