<?php

/**
 * imagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class imagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object imagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('images');
    }
}