<?php

/**
 * keywordsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class keywordsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object keywordsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('keywords');
    }
}